### ISSUE TITLE
Questions about example and setup.

### ISSUE THREAD

**Issue by pruppert** [paulomendes/EventHorizon#1]
Does this allow location simulation that applies to all iOS apps?

Also:
I run 'pod install' in Example directory and then open the Example project but get the error 

> ld: library not found for -lPods-EventHorizon-EventHorizon
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

The build fails. Any idea what's going wrong?

**Comment by pruppert** [comment]
Never mind. I was mistakenly opening EventHorizon.xcodeproj instead of EventHorizon.xcworkspace. It builds just fine from the xcworkspace.

**Comment by paulomendes** [comment]
:D
