### ISSUE TITLE
Does this affect GPS location of other iOS apps?

### ISSUE THREAD

**Issue by pruppert** [paulomendes/EventHorizon#2]
Is this meant to allow location simulation that applies to other iOS apps? It currently does not seem to affect other apps' GPS location. Thanks.

**Comment by paulomendes** [comment]
No @pruppert. This is a library that you put in your own project and start to fake locations within your app. 

The basics of this is make a Method Swizzling of didUpdateLocations of Apple CLLocationManager. When your App start do update locations, if you has enable EventHorizon, when you call

``` objc
[[EventHorizon instance] fakeLocation:location];
```

The data sent to 

```
- (void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray *)locations 
```

is the location that you passed in the argument of falkeLocation method.

**Comment by pruppert** [comment]
Ok. Thank you for the reply. :-)
